### ISSUE TITLE
Rename configure.sh

### ISSUE THREAD

**Issue by RibalGZ** [gavinhoward/bc#29]
Would it be possible to rename the "configure.sh" script to the standard "configure" form?

This change would avoid specific code when packaging it into distributions that use standard templates.

Thank you

**Comment by gavinhoward** [comment]
This is something I debated doing in the past (see [this commit][1]), but I ultimately [changed it back][2] because I want it to be clear that this is not an Autotools project.

That said, let me see what I can do for you.

What distro(s) do you want to package this for? I have already gotten it packaged into several, so it might already exist. I also might be able to package it for the distro you want.

If that won't work, I can possibly figure out a way to create a `configure` symlink to `configure.sh`.

[1]: https://github.com/gavinhoward/bc/commit/8302ea87f0a3dab3ec4112149ac25ee3104d77d2
[2]: https://github.com/gavinhoward/bc/commit/79f605c1af68ee1d834fb561fadde072e803750e

**Comment by RibalGZ** [comment]
I'm tinkering with my own distro. I already have bc working, but I wanted to know if it would be possible to use the expected file.

Thanks anyway ;)

**Comment by gavinhoward** [comment]
I will investigate whether I can use a symlink, just in case.

**Comment by gavinhoward** [comment]
It seems I can. Fixed in commit [2cd27287c92e0e46fbf9215e6930fbd27362dabb][1].

I won't release with this yet. Seems like a small thing to release for.

[1]: https://github.com/gavinhoward/bc/commit/2cd27287c92e0e46fbf9215e6930fbd27362dabb
