### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by depler** [gavinhoward/bc#46]
Hi! When are you going to release new version with recent changes?

**Comment by gavinhoward** [comment]
Yes. It will be `5.1.0`.

I have not done so yet because of two things. First, I was not really sure if you would find more bugs, and second, my release process takes a while. (It includes, among other things, building `bc` in every supported configuration and running the test suite for every build, on multiple platforms.)

I expect that the release will go out sometime today (US time).

**Comment by gavinhoward** [comment]
Release is out! Thank you for your help.

**Comment by depler** [comment]
Thanks! Why did you put project files, debug executables and test files into release archive?

**Comment by gavinhoward** [comment]
I should not have put the test files (sorry; I'll take them out next release), but I put the others there in case users *want* a debug executable. Basically, I put whatever I thought users might want even if they don't want the full repo. (I know at least Linux distro that builds a debug version of my `bc`.)

**Comment by gavinhoward** [comment]
The next release is out (there was a bug), and I have implemented your suggestions, except for debug executables. Thank you.

I will go ahead and close this bug now, but you can reopen if you feel the need.
