### ISSUE TITLE
Difference between --localedir and NLSPATH

### ISSUE THREAD

**Issue by firasuke** [gavinhoward/bc#58]
As in the title, what's the difference between the two? and why is `--localedir` only mentioned in `build.md` and not when running `./configure --help`?

**Comment by gavinhoward** [comment]
So I originally added `--localedir` because it was one of the standard GNU configure options. This was before I understood that GNU does *not* use POSIX locales.

`--localedir` does not make sense when a program is using POSIX locales, so I've [removed references to `LOCALEDIR` and friends from everything][1].

Does that answer your question?

[1]: https://github.com/gavinhoward/bc/commit/f4816582b1264b64566fc162ef6512601077cc63

**Comment by firasuke** [comment]
So `--localedir` shouldn't be used?

**Comment by gavinhoward** [comment]
You are correct; it should not be used.

It wasn't used to change anything in the Makefile, so it merely just didn't do anything. With the change I made, the configure script should more give an error if it is given.

**Comment by firasuke** [comment]
Ok cool, thanks for clarifying. Closing..
