### ISSUE TITLE
bc -> bc dependency loop

### ISSUE THREAD

**Issue by pg83** [gavinhoward/bc#63]
https://github.com/gavinhoward/bc/blob/master/scripts/safe-install.sh#L28 creates hard dependency loop on previously available bc for install process, which can be not available:

* in bootstrap environments
* in cross-compile environments

**Comment by gavinhoward** [comment]
Whoops. I did not think of that. My bad.

This should be fixed in 313738df7f6d65875dd91ef63565227d0f782472 and 349cd801d5a7f4ab2fad76096d271397aa738063. I put out `6.3.1` because I know for a fact that Linux from Scratch will need these changes too, and they usually just grab the latest release.

I hope this new release works for you. Please close this issue if it does.

**Comment by pg83** [comment]
thanx!
