### ISSUE TITLE
Feature request: elliptic curve point multiplication

### ISSUE THREAD

**Issue by GregTonoski** [gavinhoward/bc#82]
Would you like to add elliptic curve point multiplication (https://en.wikipedia.org/wiki/Elliptic_curve_point_multiplication) to math library, perhaps?

**Comment by gavinhoward** [comment]
I have wanted to, but I haven't *despite* wanting to. And there is a good reason: someone is going to use my `bc` to implement cryptography with vulnerabilities.

If my `bc` ships the elliptic curve arithmetic to do that, I will feel responsible. If they write the arithmetic themselves, well, they are responsible.

Of course, there are other reasons to want it, but because of cryptography, I hesitate to add it.

Sorry!
